language: java
jdk: oraclejdk-ea
sudo: false
before_install: chmod +x gradlew

script:
  - ./gradlew build
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
